console.log("Subirse al auto y conducir por Saenz Peña hasta calle Passo");
console.log("En calle Passo doblar a la izquierda y avanzar hasta la avenida Belgrano");
console.log("Cruzar avenida Belgrano y conducir por calle Alvear por cien metros");
console.log("Doblar a la izquierda y conducir cien metros pro calle Lucio V.Lopez");
console.log("Al llegar a avenida Belgrano, doblar a la izquierda");
console.log("Conducir por veinte metros");
console.log("Accionar luces de giro a la izquierda");
console.log("Ingresar al estacionamiento del supermercado");
console.log("Estacionar el auto");
console.log("Entrar al supermercado");